apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cicd-demo

  template:
    metadata:
      labels:
        app: cicd-demo

    spec:
      containers:
        - name: cicd-demo
          image: 260969591589.dkr.ecr.us-east-1.amazonaws.com/cicd-demo:latest
          ports:
            - containerPort: 5000